page_title                                : WorldAnimals                              # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1468446611                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : http://play.google.com                    # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app_icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : WorldAnimals                             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

t:
  en:
    app_headline: In English, the frog says "ribbit"...
    app_description: What does it say in other languages?
    language_feature_title: Supports 11 different languages
    language_feature_description: Customize which languages are used for the animal questions.
    answer_feature_title: Hear spoken answers
    answer_feature_description: Learn how to pronounce sounds with built-in recordings.
    kids_feature_title: Safe for kids
    kids_feature_description: Built with privacy in mind. No data is ever collected by the app.
    illustration_title: Hand-drawn illustrations
    illustration_description: Includes 15 different animals wearing classic hats of various countries. Tap on the animal and flag icons to see the animals that will be speaking!
    languages_title: Supported languages
    english: English
    chinese: Chinese
    french: French
    german: German
    italian: Italian
    japanese: Japanese
    korean: Korean
    norwegian: Norwegian
    russian: Russian
    spanish: Spanish
    swedish: Swedish
    footer_promo: Start your language learning now!
    footer_feedback: Feedback
    footer_privacy: Privacy Policy
    footer_contact: Contact us
    footer_rights: All rights reserved.
  zh:
    app_headline: 一只青蛙说的叫声是“呱呱”...
    app_description: What does it say in other languages?
    language_feature_title: Supports 11 different languages
    language_feature_description: Customize which languages are used for the animal questions.
    answer_feature_title: Hear spoken answers
    answer_feature_description: Learn how to pronounce sounds with built-in recordings.
    kids_feature_title: Safe for kids
    kids_feature_description: Built with privacy in mind. No data is ever collected by the app.
    illustration_title: Hand-drawn illustrations
    illustration_description: Includes 15 different animals wearing classic hats of various countries. Tap on the animal and flag icons to see the animals that will be speaking!
    languages_title: Supported languages
    english: English
    chinese: Chinese
    french: French
    german: German
    italian: Italian
    japanese: Japanese
    korean: Korean
    norwegian: Norwegian
    russian: Russian
    spanish: Spanish
    swedish: Swedish
    footer_promo: Start your language learning now!
    footer_feedback: Feedback
    footer_privacy: Privacy Policy
    footer_contact: Contact us
    footer_rights: All rights reserved.


# Information About Yourself
your_name                                 : Vivian Qu                                
your_link                                 : https://vivqu.com                     
your_city                                 :                          
email_address                             : hello@worldanimalsapp.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : vivqu
github_username                           : vivqu
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : language_feature_title 
    description                           : language_feature_description 
    fontawesome_icon_name                 : language

  - title                                 : answer_feature_title
    description                           : answer_feature_description
    fontawesome_icon_name                 : volume-up

  - title                                 : kids_feature_title
    description                           : kids_feature_description
    fontawesome_icon_name                 : baby


# Image List
illustrations                             :
  - icon                                  : assets/illustrations/lion-head.png
    animalName                            : lion
  - icon                                  : assets/illustrations/cow-head.png
    animalName                            : cow
  - icon                                  : assets/illustrations/sheep-head.png
    animalName                            : sheep
  - icon                                  : assets/illustrations/pig-head.png
    animalName                            : pig
  - icon                                  : assets/illustrations/duck-head.png
    animalName                            : duck

# Supported languages list
languages                                 :
  - title: English
    localized: English
  - title: Chinese
    localized: 中文
  - title: French
    localized: Français
  - title: German
    localized: Deutsch
  - title: Italian
    localized: Italiano
  - title: Japanese
    localized: 日本語
  - title: Korean
    localized: 한국어
  - title: Norwegian
    localized: Norsk språk
  - title: Russian
    localized: русский
  - title: Spanish
    localized: Español
  - title: Swedish
    localized: Svenska språket


# Theme Settings
header_title_color                        : "#ffffff"
body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_headline_color                     : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
